onboarding = false

[theme]
name = "terminal"
auto_switch = false

[theme.custom]
accent = "#E11A45"
red = "#E11A45"
selection_bg = "#E11A45"
active_row_bg = "#E11A45"
surface_dim = "#E11A45"
text = "#E6E6E6"

[ui]
agent_panel_sort = "priority"
tab_bar_position = "top"

[keys]
prefix = "ctrl+a"
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "herdr-nvim-nav.left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "herdr-nvim-nav.down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "herdr-nvim-nav.up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "herdr-nvim-nav.right"
