onboarding = false

[theme]
name = "terminal"
auto_switch = false

[ui]
agent_panel_sort = "priority"
tab_bar_position = "top"

[keys]
prefix = "ctrl+a"
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "herdr-nvim-nav.left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "herdr-nvim-nav.down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "herdr-nvim-nav.up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "herdr-nvim-nav.right"

[[keys.command]]
key = "prefix+t"
type = "plugin_action"
command = "herdr-theme-picker.open"

[theme.custom]
panel_bg = "#000000"
sidebar_bg = "#000000"
active_row_bg = "#E11A45"
selection_bg = "#E11A45"
surface0 = "#000000"
surface1 = "#000000"
surface_dim = "#000308"

# Pasos para poner borde inactivo de color personalizado:
# 1. Poner #1a1a1a en overlay0, ejecutar comando "herdr server reload-config".
# 2. Poner #ffffff en overlay0, cerrar y abrir ghostty.
overlay0 = "#ffffff" 

overlay1 = "#000000"
text = "#e6edf3"
subtext0 = "#b1bac4"
accent = "#E11A45"
mauve = "#000000"
green = "#E11A45"
yellow = "#d29922"
red = "#E11A45"
blue = "#E11A45"
teal = "#E11A45"
peach = "#ffa198"
